package com.mycompany.MenuPrincipal;

import com.mycompany.ActualizarLibroDiario.AgregarLibroDiario;
import com.mycompany.LibroDiario.LibroDiario;
import com.mycompany.LibroMayor.LibroMayor;
import com.mycompany.Archivo.Archivo;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author aspxe
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public int cuentaNum = 0, chequeNum = 0;
    public double cargoOAbono = 0;
    public String fecha = "", descripcion = "", titulo = "", mes = "";

    public MenuPrincipal() {
        initComponents();
        //Hacemos no visible y no disponibles este label y txtfield
        lblMonto.setVisible(false);
        txtMonto.setVisible(false);
        txtMonto.setEnabled(false);
        lblTitulo.setVisible(false);
        txtTitulo.setVisible(false);
        txtTitulo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCuentaNum = new javax.swing.JLabel();
        lblChequeNum = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblCargoOAbono = new javax.swing.JLabel();
        txtNumeroCuenta = new javax.swing.JTextField();
        txtNumeroCheque = new javax.swing.JTextField();
        cbCargoOAbono = new javax.swing.JComboBox<>();
        cbDia = new javax.swing.JComboBox<>();
        cbMes = new javax.swing.JComboBox<>();
        cbYear = new javax.swing.JComboBox<>();
        lblMes = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        btnAgregarLIbroDiario = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblLibroMayor = new javax.swing.JLabel();
        lblYearLIbroMayor = new javax.swing.JLabel();
        cbYearLibroMayor = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        txtDescripcion = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnActualizar = new javax.swing.JMenu();
        btnActualizarLibroDiario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Prinicpal Contabilidad");
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(20, 20));
        setPreferredSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(null);

        lblCuentaNum.setText("Numero de cuenta");
        getContentPane().add(lblCuentaNum);
        lblCuentaNum.setBounds(20, 30, 140, 18);

        lblChequeNum.setText("Numero de cheque");
        getContentPane().add(lblChequeNum);
        lblChequeNum.setBounds(20, 120, 124, 18);

        lblDia.setText("Dia");
        getContentPane().add(lblDia);
        lblDia.setBounds(220, 30, 41, 18);

        lblDescripcion.setText("Descripcion");
        getContentPane().add(lblDescripcion);
        lblDescripcion.setBounds(20, 200, 78, 18);

        lblCargoOAbono.setText("Cargo o abono");
        getContentPane().add(lblCargoOAbono);
        lblCargoOAbono.setBounds(580, 30, 100, 18);
        getContentPane().add(txtNumeroCuenta);
        txtNumeroCuenta.setBounds(20, 60, 140, 24);
        getContentPane().add(txtNumeroCheque);
        txtNumeroCheque.setBounds(20, 150, 140, 24);

        cbCargoOAbono.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cargo", "Abono" }));
        cbCargoOAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCargoOAbonoActionPerformed(evt);
            }
        });
        getContentPane().add(cbCargoOAbono);
        cbCargoOAbono.setBounds(590, 70, 77, 30);

        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cbDia);
        cbDia.setBounds(210, 60, 72, 24);

        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        getContentPane().add(cbMes);
        cbMes.setBounds(300, 60, 111, 24);

        cbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2021", "2022", "2023" }));
        getContentPane().add(cbYear);
        cbYear.setBounds(440, 60, 72, 24);

        lblMes.setText("Mes");
        getContentPane().add(lblMes);
        lblMes.setBounds(330, 30, 27, 18);

        lblYear.setText("Año");
        getContentPane().add(lblYear);
        lblYear.setBounds(450, 30, 25, 18);

        lblMonto.setText("jLabel2");
        getContentPane().add(lblMonto);
        lblMonto.setBounds(320, 120, 130, 18);
        getContentPane().add(txtMonto);
        txtMonto.setBounds(320, 150, 130, 24);

        btnAgregarLIbroDiario.setText("Agregar");
        btnAgregarLIbroDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLIbroDiarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarLIbroDiario);
        btnAgregarLIbroDiario.setBounds(310, 300, 170, 24);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 360, 690, 20);

        lblLibroMayor.setText("Ingrese el año del libro mayor que desea consultar");
        getContentPane().add(lblLibroMayor);
        lblLibroMayor.setBounds(150, 390, 350, 18);

        lblYearLIbroMayor.setText("Año");
        getContentPane().add(lblYearLIbroMayor);
        lblYearLIbroMayor.setBounds(310, 420, 25, 18);

        cbYearLibroMayor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2021", "2022", "2023" }));
        getContentPane().add(cbYearLibroMayor);
        cbYearLibroMayor.setBounds(290, 450, 72, 24);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(290, 500, 77, 24);
        getContentPane().add(txtDescripcion);
        txtDescripcion.setBounds(20, 240, 200, 70);

        lblTitulo.setText("Titulo de la cuenta");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(320, 200, 140, 18);
        getContentPane().add(txtTitulo);
        txtTitulo.setBounds(320, 230, 140, 24);

        btnActualizar.setText("Actualizar libro");

        btnActualizarLibroDiario.setText("Actualizar libro diario");
        btnActualizarLibroDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarLibroDiarioActionPerformed(evt);
            }
        });
        btnActualizar.add(btnActualizarLibroDiario);

        jMenuBar1.add(btnActualizar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCargoOAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCargoOAbonoActionPerformed
        int seleccion = cbCargoOAbono.getSelectedIndex();
        if (seleccion == 0) {
            lblMonto.setVisible(true);
            lblMonto.setText("Monto del cargo");
            txtMonto.setVisible(true);
            txtMonto.setEnabled(true);
            lblTitulo.setVisible(true);
            txtTitulo.setVisible(true);
            txtTitulo.setEnabled(true);
        } else {
            lblMonto.setVisible(true);
            lblMonto.setText("Monto del abono");
            txtMonto.setVisible(true);
            txtMonto.setEnabled(true);
            lblTitulo.setVisible(true);
            txtTitulo.setVisible(true);
            txtTitulo.setEnabled(true);
        }
    }//GEN-LAST:event_cbCargoOAbonoActionPerformed
    //La funcion ya crea el archivo .dat :) por fin
    private void btnAgregarLIbroDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLIbroDiarioActionPerformed
        //Asegurarnos de que el usuario ingrese un numero de cuenta, cheque, descripcion y monto

        int seleccionDia = 0, seleccionMes = 0, seleccionYear = 0;
        LibroDiario ld = new LibroDiario();
        LibroMayor lm = new LibroMayor();
        MenuPrincipal mp = new MenuPrincipal();

        if (txtNumeroCuenta.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe de agregar un numero de cuenta", "Numero de cuenta faltante", JOptionPane.ERROR_MESSAGE);
        } else {
            this.cuentaNum = Integer.parseInt(txtNumeroCuenta.getText());
            ld.setCuentaNum(this.cuentaNum);
            lm.setCuentaNum(this.cuentaNum);
        }
        if (txtNumeroCheque.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe de agregar un numero de cheque", "Numero de cheque faltante", JOptionPane.ERROR_MESSAGE);
        } else {
            this.chequeNum = Integer.parseInt(txtNumeroCheque.getText());
            ld.setChequeNum(this.chequeNum);
        }
        if (txtDescripcion.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe de agregar una descripcion", "Descripcion faltante", JOptionPane.ERROR_MESSAGE);
        } else {
            this.descripcion = txtDescripcion.getText();
            ld.setDescripcion(this.descripcion);
        }
        if (txtMonto.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe de agregar el monto del movimiento", "Monto del movimiento no ingresado", JOptionPane.ERROR_MESSAGE);
        } else {
            this.cargoOAbono = Double.parseDouble(txtMonto.getText());
            if (cbCargoOAbono.getSelectedIndex()==0) {
                ld.setCargoOAbono(-(this.cargoOAbono));
                lm.setMontoMes(-(this.cargoOAbono));
            } else if (cbCargoOAbono.getSelectedIndex()==1) {
                ld.setCargoOAbono((this.cargoOAbono));
                lm.setMontoMes((this.cargoOAbono));
            }

        }
        if (txtTitulo.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe de agregar un titulo de cuenta", "Titulo de la cuenta no ingresado", JOptionPane.ERROR_MESSAGE);
        } else {
            this.titulo = txtTitulo.getText();
            lm.setTituloCuenta(this.titulo);
        }

        seleccionDia = cbDia.getSelectedIndex();
        seleccionMes = cbMes.getSelectedIndex();
        seleccionYear = cbYear.getSelectedIndex();
        this.fecha = cbDia.getItemAt(seleccionDia) + "/" + cbMes.getItemAt(seleccionMes) + "/" + cbYear.getItemAt(seleccionYear);
        this.mes = cbMes.getItemAt(seleccionMes);
        lm.setMes(this.mes);

        ld.setFecha(this.fecha);
        Archivo arch = new Archivo();

        arch.agregarLibroDiario("LibroDiario-" + cbDia.getItemAt(seleccionDia) + "-" + cbMes.getItemAt(seleccionMes) + "-" + cbYear.getItemAt(seleccionYear) + ".dat", ld);

        try {
            arch.agregarAlLibroMayor("LibroMayor-" + cbYear.getItemAt(seleccionYear) + ".dat", ld, lm, mp);
            arch.reporteLibroDiario("LibroDiario-" + cbDia.getItemAt(seleccionDia) + "-" + cbMes.getItemAt(seleccionMes) + "-" + cbYear.getItemAt(seleccionYear) + ".dat");
        } catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAgregarLIbroDiarioActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Archivo arch = new Archivo();
        int seleccionYear = cbYearLibroMayor.getSelectedIndex();
        String nombreArchivo = "LibroMayor-" + cbYearLibroMayor.getItemAt(seleccionYear) + ".dat";
        try {
            arch.reporteLibroMayor(nombreArchivo);
        } catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarLibroDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarLibroDiarioActionPerformed
        AgregarLibroDiario ald = new AgregarLibroDiario();
        ald.setVisible(true);
    }//GEN-LAST:event_btnActualizarLibroDiarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    public String getMes() {
        return this.mes;
    }

    public void setMes(String mes) {
        this.mes = mes;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnActualizar;
    private javax.swing.JMenuItem btnActualizarLibroDiario;
    private javax.swing.JButton btnAgregarLIbroDiario;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cbCargoOAbono;
    private javax.swing.JComboBox<String> cbDia;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JComboBox<String> cbYear;
    private javax.swing.JComboBox<String> cbYearLibroMayor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCargoOAbono;
    private javax.swing.JLabel lblChequeNum;
    private javax.swing.JLabel lblCuentaNum;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblLibroMayor;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblYear;
    private javax.swing.JLabel lblYearLIbroMayor;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNumeroCheque;
    private javax.swing.JTextField txtNumeroCuenta;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
